# Generated by Django 2.1.15 on 2020-11-24 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('localization', models.CharField(max_length=255, verbose_name='Kraków')),
                ('status', models.CharField(choices=[('W', 'W trakcie'), ('Z', 'Zakończony'), ('P', 'Przerwany')], default='W', max_length=1)),
                ('date_started', models.DateField(auto_now=True)),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
