# Generated by Django 3.1.4 on 2021-01-22 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('localization', models.CharField(default='Kraków', max_length=255)),
                ('status', models.CharField(choices=[('W', 'W trakcie'), ('Z', 'Zakończony'), ('P', 'Przerwany')], default='W', max_length=1)),
                ('date_started', models.DateField()),
                ('value', models.IntegerField()),
                ('investor', models.CharField(blank=True, max_length=600)),
                ('project_object', models.CharField(blank=True, max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('zlecenie_z_gazowni', models.BooleanField(default=False)),
                ('warunki_techniczne', models.BooleanField(default=False)),
                ('wypis_i_wyrys', models.BooleanField(default=False)),
                ('mapa', models.BooleanField(default=False)),
                ('zgody_właścicieli_działki', models.BooleanField(default=False)),
                ('zmiana_warunków_technicznych', models.BooleanField(default=False)),
                ('decyzja_lokalizacyjna', models.BooleanField(default=False)),
                ('zudp', models.BooleanField(default=False)),
                ('służebność_przesyłu', models.BooleanField(default=False)),
                ('konserwator_zabytków', models.BooleanField(default=False)),
                ('wody_polskie', models.BooleanField(default=False)),
                ('projekt_geotechniczny', models.BooleanField(default=False)),
                ('wejście_w_teren', models.BooleanField(default=False)),
                ('organizacja_ruchu', models.BooleanField(default=False)),
                ('opracowanie_projektu_budowlanego', models.BooleanField(default=False)),
                ('uzgodnienie_projektu_w_PSG', models.BooleanField(default=False)),
                ('uzgodnienie_projektu_u_zarządcy_drogi', models.BooleanField(default=False)),
                ('pozwolenie_na_budowe', models.BooleanField(default=False)),
                ('zaświadczenie_o_nie_wniesieniu_sprzeciwu_wobec_zgłoszenia', models.BooleanField(default=False)),
                ('dziennik_budowy', models.BooleanField(default=False)),
                ('zdjęcie_pasa_drogowego', models.BooleanField(default=False)),
                ('umieszczenie_infrastruktury_technicznej_w_pasie_drogowym', models.BooleanField(default=False)),
                ('wykonanie_robót_w_terenie', models.BooleanField(default=False)),
                ('szkice_powykonawcze', models.BooleanField(default=False)),
                ('zgłoszenie_zakończenia_budowy_do_PINB', models.BooleanField(default=False)),
                ('zaświadczenie_o_braku_sprzeciwu_wobec_użytkowania', models.BooleanField(default=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('O', 'Opłacony'), ('D', 'Do opłacenia')], default='D', max_length=1)),
                ('invoice', models.FileField(upload_to='media/invoices/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='media/project_files/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
    ]
