# Generated by Django 2.1.15 on 2020-11-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='price',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='project',
            name='localization',
            field=models.CharField(default='Kraków', max_length=255),
        ),
    ]
