# Generated by Django 3.1.4 on 2020-12-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201213_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='investor',
            field=models.CharField(default='Default', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_object',
            field=models.CharField(default='Default', max_length=2000),
            preserve_default=False,
        ),
    ]
