# Generated by Django 3.1.4 on 2020-12-13 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201213_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zlecenie_z_gazowni', models.BooleanField(default=False)),
                ('warunki_techniczne', models.BooleanField(default=False)),
                ('wypis_i_wyrys', models.BooleanField(default=False)),
                ('mapa', models.BooleanField(default=False)),
                ('zup', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='checklist',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.checklist'),
            preserve_default=False,
        ),
    ]
