# Generated by Django 3.1.4 on 2020-12-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201213_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='checklist_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklist',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
    ]
