# Generated by Django 3.1.4 on 2020-12-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201213_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='checklist_id',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.project'),
        ),
    ]
