# Generated by Django 3.1.4 on 2020-12-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_projectfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectFiles',
            new_name='ProjectFile',
        ),
    ]
