# Generated by Django 3.1.4 on 2020-12-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201214_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='uzyskanie_zgod',
            field=models.BooleanField(default=False),
        ),
    ]
